### ISSUE TITLE
Fan switches back to Default Profile after waking from Sleep

### ISSUE THREAD

**Issue by baldsealion** [ayufan-research/steam-deck-tools#1]
Great app, this is fantastic progress-- One issue encountered though when waking from sleep, it switched back to Default profile and I have to manually switch it back to SteamOS profile

This is the steps to repeat:

- Fan is slow/quiet(working with SteamOS profile)
- Sleep
- Unsleep
- Tooltip shows previous RPM, but fan is noticeably faster
- Open the window
- Tooltip will start showing the proper RPM
- Switch profile to "SteamOS" again, (even if it's already selected)
- Fan goes slow/quiet again

**Comment by CelesteHeartsong** [comment]
I can confirm this was happening with me on my deck when trying.  @baldsealion:  Once you have a chance to try the app out, perhaps we can see if this is something with just my deck or happening across multiple users.

**Comment by ayufan** [comment]
This is fixed by https://github.com/ayufan-research/steam-deck-tools/releases/tag/0.1.6.
