### ISSUE TITLE
Triple digit FPS is messed up a little

### ISSUE THREAD

**Issue by baldsealion** [ayufan-research/steam-deck-tools#3]
Really minor complaint but just making you aware. If a game reaches higher than 99 fps; the first digit is grey and there are grey numbers behind the 2nd and 3rd digit the example picture should be 260fps 
![42D0DF71-6B05-402E-B943-413496A6149F](https://user-images.githubusercontent.com/93551277/202064736-5971e4f2-431a-4f7b-801f-f91f0756a49c.jpeg)

**Comment by crowland1978** [comment]
This error is also happens more on the fan numbers and if you switch from overlay min to full the info just stays on screen.h
![IMG_20230930_220720](https://github.com/ayufan/steam-deck-tools/assets/81024429/9305b783-d28f-41fd-a354-a2afd562387e)
